version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ frontend"
  - package-ecosystem: "npm"
    directory: "/backend/services/core"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ backend"
      