FROM node:16-alpine

RUN apk add curl
HEALTHCHECK CMD curl -f http://localhost:3000/api/health || exit 1

WORKDIR /project/app

ENV NODE_ENV=production

COPY ./frontend ./

RUN npm ci && npm run build

CMD npm start