FROM node:16-alpine

RUN apk add curl
HEALTHCHECK CMD curl -f http://localhost:3000/api/health || exit 1

WORKDIR /project/app

ENV NODE_ENV=production

COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm ci --no-audit --progress=false

COPY ./frontend ./
RUN npm run build

COPY ./.git ../.git
CMD npm start