const routes = {
  root: '/',
  contactUs: '/contact-us',
  webshop: '/webshop',
  cart: '/webshop/cart',
  checkout: '/webshop/checkout',
  awaitPayment: (paymentId: string) => `/webshop/await-payment/${paymentId}`,
  onboarding: '/onboarding',
  article: (articleId: string, scrollToComments?: boolean) => `/news/article/${articleId}${scrollToComments ? '#comments-section' : ''}`,
  articleRequests: '/news/requests',
  member: (memberId) => `/members/${memberId}`,
  settings: '/settings',
  pings: '/pings',
  memberChest: (studentId) => `/members/${studentId}/chest`,
  editMember: (memberId) => `/members/${memberId}/edit`,
  changeProfilePicture: (memberId) => `/members/${memberId}/change-profile-picture`,
  news: '/news',
  editArticle: (articleId) => `/news/article/${articleId}/edit`,
  newsAdmin: '/news/admin',
  tags: '/news/admin/tags',
  editTag: (tagId) => `/news/admin/tags/${tagId}`,
  createTag: '/news/admin/tags/create',
  createArticle: '/news/article/create',
  mandateByYear: (year) => `/mandates/${year}`,
  volunteerAccess: '/volunteer-info/access',
  volunteerBenefits: '/volunteer-info/benefits',
  volunteerOther: '/volunteer-info/other',
  committees: '/committees',
  committeePage: (committeeId) => `/committees/${committeeId}`,
  position: (positionId) => `/positions/${positionId}`,
  editPosition: (positionId) => `/positions/${positionId}/edit`,
  events: '/events',
  passedEvents: '/events/passed',
  event: (eventId) => `/events/${eventId}`,
  editEvent: (eventId) => `/events/${eventId}/edit`,
  createEvent: '/events/create',
  documents: '/documents',
  statutes:
    '/stadgar',
  regulations:
    '/reglemente',
  governingDocuments: '/documents/governing',
  newGoverningDocument: '/documents/governing/new',
  editGoverningDocument: (id) => `/documents/governing/${id}/edit`,
  srd: '/documents/srd',
  kravprofiler: '/documents/kravprofiler',
  meetingDocuments: '/documents',
  calendar: '/calendar',
  calendarDownload: (langaugeCode) => `/api/calendar/download/${langaugeCode}`,
  searchApi: '/api/search',
  eventsSearchApi: '/api/searchevents',
  articlesSearchApi: '/api/searcharticles',
  booking: '/booking',
  bookables: '/booking/bookables',
  editBookable: (id) => `/booking/bookables/${id}`,
  createBookable: '/booking/bookables/create',
  doors: '/doors/edit',
  editApis: '/apis/edit',
  archive: '#archive',
  photos: '/photos',
  songs: '/songs',
  song: (title) => `/songs/${title}`,
  cafe: '/cafe',
  mailAlias: '/mail-alias/edit',
  markdownsAdmin: '/markdowns/admin',
  adminSettings: '/admin/settings',

  // App-only
  guild: '/guild',
  account: '/account',

  // Nollning
  nolla: {
    home: '/nolla',
    nollningen: '/nolla/nollningen',
    registration: '/nolla/registration',
    accomodation: '/nolla/accomodation',
    guild: '/nolla/guild',
    packinglist: '/nolla/packinglist',
    checklist: '/nolla/checklist',
    pepparna: '/nolla/pepparna',
    studenthealth: '/nolla/studenthealth',
    faq: '/nolla/faq',
  },
};
export default routes;
