version: "3"
services:
  database:
    volumes:
      - "dbdata:/var/lib/postgres"
  migrator:
    restart: always
    build:
      dockerfile: ./backend/migrator/Dockerfile.prod
  core:
    restart: always
    build:
      dockerfile: ./backend/services/core/Dockerfile.prod
  gateway:
    restart: always
    build:
      dockerfile: ./backend/gateway/Dockerfile.prod
  frontend:
    restart: always
    build:
      dockerfile: ./frontend/Dockerfile.prod
  minio1:
    volumes:
      - /minio/data1-1:/data
volumes:
  dbdata:
