version: "3"
volumes:
  data1-1:
services:
  core:
    build:
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/backend
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/frontend
  minio1:
    volumes:
      - data1-1:/data1
