version: '3.7'

x-minio-common: &minio-common
  image: minio/minio:RELEASE.2021-07-22T05-23-32Z
  command: server --console-address ":9001" /data
  expose:
    - "9000"
    - "9001"
  networks:
      - files
  env_file: .env
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --label-enable --interval 3600
    labels:
      - com.centurylinklabs.watchtower.enable=true
  database:
    image: "postgres:${POSTGRES_VERSION}-alpine"
    volumes:
      - "postgress/website:/var/lib/postgres"
    networks:
      - local
    env_file: .env
    ports:
      - 5432:5432
    labels:
      - com.centurylinklabs.watchtower.enable=true

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    depends_on:
      - database
    ports:
      - 5050:80
    labels:
      - com.centurylinklabs.watchtower.enable=true

  migrator:
    depends_on:
      - database
    image: imagerepo.dsek.se/migrator:latest
    env_file: .env
    networks:
      - local
    labels:
      - com.centurylinklabs.watchtower.enable=true

  core:
    depends_on:
      - database
    image: imagerepo.dsek.se/core:latest
    restart: always
    env_file: .env
    networks:
      - local
    labels:
      - com.centurylinklabs.watchtower.enable=true

  news:
    depends_on:
      - database
    image: imagerepo.dsek.se/news:latest
    restart: always
    env_file: .env
    networks:
      - local
    labels:
      - com.centurylinklabs.watchtower.enable=true

  calendar:
    depends_on:
      - database
    image: imagerepo.dsek.se/calendar:latest
    restart: always
    env_file: .env
    networks:
      - local
    labels:
      - com.centurylinklabs.watchtower.enable=true

  booking:
    depends_on:
      - database
    image: imagerepo.dsek.se/booking:latest
    restart: always
    env_file: .env
    networks:
      - local
    labels:
      - com.centurylinklabs.watchtower.enable=true

  file-handler:
    depends_on:
      - database
    image: imagerepo.dsek.se/file-handler:latest
    restart: always
    env_file: .env
    networks:
      - local
    labels:
      - com.centurylinklabs.watchtower.enable=true

  gateway:
    image: imagerepo.dsek.se/gateway:latest
    restart: always
    ports:
      - '4000:4000'
    networks:
      - local
    depends_on:
      - core
      - news
      - calendar
      - booking
      - database
      - file-handler
    env_file: .env
    environment:
      SERVICE_URL_0: http://core:4000/
      SERVICE_NAME_0: core
      SERVICE_URL_1: http://news:4000/
      SERVICE_NAME_1: news
      SERVICE_URL_2: http://calendar:4000/
      SERVICE_NAME_2: calendar
      SERVICE_URL_3: http://booking:4000/
      SERVICE_NAME_3: booking
      SERVICE_URL_4: http://file_handler:4000/
      SERVICE_NAME_4: file_handler
    labels:
      - com.centurylinklabs.watchtower.enable=true

  frontend:
    image: imagerepo.dsek.se/frontend:latest
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - gateway
    env_file: .env
    labels:
      - com.centurylinklabs.watchtower.enable=true

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - /minio/data1-1:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true

  files:
    image: imagerepo.dsek.se/files:latest
    restart: always
    ports:
      - "9000:9000"
    networks:
      - local
      - files
    depends_on:
      - minio1
    labels:
      - com.centurylinklabs.watchtower.enable=true
networks:
  files:
    driver: bridge
  local:
    driver: bridge