version: '3.7'

services:

  memberpage:
    container_name: memberpage
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      - gateway

networks:
  gateway:
    external:
      name: gateway
