version: "3"
services:
  database:
    volumes:
      - "dbdata:/var/lib/postgres"
  migrator:
    restart: always
    build:
      dockerfile: ./backend/migrator/Dockerfile.prod
  core:
    restart: always
    build:
      dockerfile: ./backend/services/core/Dockerfile.prod
  news:
    restart: always
    build:
      dockerfile: ./backend/services/news/Dockerfile.prod
  calendar:
    restart: always
    build:
      dockerfile: ./backend/services/calendar/Dockerfile.prod
  booking:
    restart: always
    build:
      dockerfile: ./backend/services/booking/Dockerfile.prod
  file_handler:
    restart: always
    build:
      dockerfile: ./backend/services/file-handler/Dockerfile.prod
  gateway:
    restart: always
    build:
      dockerfile: ./backend/gateway/Dockerfile.prod
  frontend:
    restart: always
    build:
      dockerfile: ./frontend/Dockerfile.prod
  minio1:
    volumes:
      - /minio/data1-1:/data
volumes:
  dbdata: