version: '3'
services:
  migrator:
    build:
      dockerfile: ./backend/migrator/Dockerfile
    volumes:
      - ./backend/migrator/src:/project/app/src
      - ./backend/migrator/migrations:/project/app/migrations
      - ./backend/migrator/seeds:/project/app/seeds
      - ./backend/shared/dist:/project/shared/dist
  core:
    build:
      dockerfile: ./backend/services/core/Dockerfile
    volumes:
      - ./backend/services/core/src:/project/app/src
      - ./backend/shared/dist:/project/shared/dist
  news:
    build:
      dockerfile: ./backend/services/news/Dockerfile
    volumes:
      - ./backend/services/news/src:/project/app/src
      - ./backend/shared/dist:/project/shared/dist
  calendar:
    build:
      dockerfile: ./backend/services/calendar/Dockerfile
    volumes:
      - ./backend/services/calendar/src:/project/app/src
      - ./backend/shared/dist:/project/shared/dist
  booking:
    build:
      dockerfile: ./backend/services/booking/Dockerfile
    volumes:
      - ./backend/services/booking/src:/project/app/src
      - ./backend/shared/dist:/project/shared/dist
  file_handler:
    build:
      dockerfile: ./backend/services/fileHandler/Dockerfile
    volumes:
      - ./backend/services/fileHandler/src:/project/app/src
      - ./backend/shared/dist:/project/shared/dist
  gateway:
    build:
      dockerfile: ./backend/gateway/Dockerfile
    volumes:
      - ./backend/gateway/src:/project/app/src
      - ./backend/shared/dist:/project/shared/dist
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/project/app
      - /app/node_modules
      - /app/.next