version: '3.1'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio:RELEASE.2021-11-24T23-19-33Z
  command: server --console-address ":9001" /data
  expose:
    - "9000"
    - "9001"
  networks:
      - files
  env_file: .env
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 1 docker container running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1


# how to add more containers
 # minio2:
 #   <<: *minio-common
 #   hostname: minio2
 #   volumes:
 #     - /minio/data2-1:/data1
 #     - /minio/data2-2:/data2

  files:
    build:
      context: .
      dockerfile: ./backend/files/Dockerfile
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - local
      - files
    depends_on:
      - minio1

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.

networks:
  files:
    driver: bridge