version: "3"
volumes:
  data1-1:
services:
  core:
    build:
      dockerfile: ./backend/services/core/Dockerfile
    volumes:
      - ./backend/services/core:/backend
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/frontend
  minio1:
    volumes:
      - data1-1:/data1
