version: "3"
volumes:
  data1-1:
services:
  core:
    build:
      dockerfile: ./backend/services/core/Dockerfile
    volumes:
      - ./backend/services/core/src:/project/app/src
      - ./backend/services/core/migrations:/project/app/migrations
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/project/app
      - /app/node_modules
      - /app/.next
  minio1:
    volumes:
      - data1-1:/data1
