version: "3.1"

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    privileged: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
      - /root/.docker/config.json:/config.json:Z
    command: --label-enable --interval 3600
    labels:
      - com.centurylinklabs.watchtower.enable=true
  autoheal:
    container_name: autoheal
    privileged: true
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
  database:
    image: "postgres:${POSTGRES_VERSION}-alpine"
    restart: always
    volumes:
      - /postgres/website:/var/lib/postgresql/data:Z
    networks:
      - local
    env_file: .env
    ports:
      - 5432:5432
    labels:
      - com.centurylinklabs.watchtower.enable=true

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    restart: always
    networks:
      - local
    depends_on:
      - database
    ports:
      - 5050:80
    labels:
      - com.centurylinklabs.watchtower.enable=true

  search:
    image: "getmeili/meilisearch:v0.25.0"
    restart: always
    privileged: true
    networks:
      - local
    env_file: .env
    volumes:
      - /data.ms/:/data.ms/:Z
    depends_on:
      - database
    ports:
      - 7700:7700
    labels:
      - com.centurylinklabs.watchtower.enable=true

  core:
    depends_on:
      - database
    image: imagerepo.dsek.se/core:latest
    restart: always
    ports:
      - "4000:4000"
    env_file: .env
    networks:
      - local
      - files

  frontend:
    image: imagerepo.dsek.se/frontend:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - core
    env_file: .env

  minio1:
    image: minio/minio:RELEASE.2021-11-24T23-19-33Z
    command: server --console-address ':9001' /data
    expose:
      - "9000"
      - "9001"
    restart: always
    networks:
      - files
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio1
    volumes:
      - /minio/data1-1:/data:Z
    labels:
      - com.centurylinklabs.watchtower.enable=true

  files:
    image: imagerepo.dsek.se/files:latest
    restart: always
    ports:
      - "9000:9000"
    networks:
      - local
      - files
    depends_on:
      - minio1
networks:
  files:
    driver: bridge
  local:
    driver: bridge
