version: "3"
services:
  database:
    image: "postgres:${POSTGRES_VERSION}-alpine"
    networks:
      - local
    env_file: .env
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    depends_on:
      - database
    ports:
      - 5050:80
  core:
    depends_on:
      - database
    build:
      context: .
    ports:
      - "4000:4000"
    env_file: .env
    networks:
      - local
  search:
    image: getmeili/meilisearch:v0.25.0
    depends_on:
      - database
    restart: always
    env_file:
      - .env
    volumes:
      - "meilidata:/data.ms"
    networks:
      - local
    ports:
      - 7700:7700
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - core
    env_file: .env
    networks: 
      - local
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  meilidata:
networks:
  local:
    driver: bridge
