FROM node:16-alpine

RUN apk add curl
HEALTHCHECK CMD curl -f http://localhost:4000/graphql?query=%7B__typename%7D || exit 1

WORKDIR /project/app

ENV NODE_ENV=production

RUN apk add --no-cache --virtual .gyp python3 make g++

COPY ./backend/package.json ./backend/package-lock.json ./
RUN npm ci --no-audit

COPY ./backend ./
RUN npm run build

RUN apk del .gyp

CMD npm start