FROM node:16-alpine

WORKDIR /project/app

ENV NODE_ENV=production

COPY ./backend/migrator ./
COPY ./backend/shared ../shared
RUN cd ../shared && npm ci && npm run build && cd ../app && npm install ../shared && npm ci


CMD npm start -- migrate minio