FROM node:lts-alpine

WORKDIR /project/app

ENV NODE_ENV=production

COPY ./backend/migrator ./
COPY ./backend/shared ../shared
RUN cd ../shared && npm ci && npm run build

RUN npm install ../shared
RUN npm ci

CMD npm start -- migrate