FROM node:16-alpine

RUN apk add curl
HEALTHCHECK CMD curl -f http://localhost:4000/graphql?query=%7B__typename%7D || exit 1

WORKDIR /project/app

ENV NODE_ENV=production

COPY ./backend/services/file-handler ./
COPY ./backend/shared ../shared

RUN apk add --no-cache --virtual .gyp python3 make g++
RUN cd ../shared && npm ci && npm run build

RUN npm install ../shared
RUN npm ci
RUN apk del .gyp

RUN npm run build

CMD npm start