FROM node:16-alpine

RUN apk add curl
HEALTHCHECK CMD curl -f http://localhost:4000/.well-known/apollo/server-health || exit 1

WORKDIR /project/app

ENV NODE_ENV=production

COPY ./backend/services/news ./
COPY ./backend/shared ../shared
RUN cd ../shared && npm ci && npm run build && cd ../app && npm install ../shared && npm ci && npm run build

CMD npm start