FROM node:16-alpine

RUN apk add curl
HEALTHCHECK CMD curl -f http://localhost:4000/.well-known/apollo/server-health || exit 1

WORKDIR /project/app

ENV NODE_ENV=production

COPY ./backend/gateway ./
COPY ./backend/shared ../shared
RUN cd ../shared && npm ci && npm run build

RUN npm install ../shared
RUN npm ci

RUN npm run build

CMD ./wait-for-services.sh && npm start