FROM node:16-alpine


WORKDIR /project/app

ENV NODE_ENV=production

COPY ./backend/services/core ./
COPY ./backend/shared ../shared
RUN apk add --update --no-cache python2 && ln -sf python2 /usr/bin/python
RUN python2 -m ensurepip
RUN pip2 install --no-cache --upgrade pip setuptools
RUN cd ../shared && npm ci && npm run build

RUN npm install ../shared
RUN npm ci

RUN npm run build

CMD npm start