FROM node:16-alpine


WORKDIR /project/app

ENV NODE_ENV=production

COPY ./backend/services/booking ./
COPY ./backend/shared ../shared
RUN apk add python make gcc g++
RUN cd ../shared && npm ci && npm run build

RUN npm install ../shared
RUN npm ci

RUN npm run build

CMD npm start