name: Make sure app queries are still valid

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, stage]

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run test-app